### ISSUE TITLE
Question: Do multiple separate script tags share the same exported global?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/origami-build-service#118]
If I have this script tag:

```html
<script async src="https://origami-build.ft.com/v2/bundles/js?modules=o-tracking"></script>
```

...then later I dynamically add another script tag to load another Origami module:

```html
<script async src="https://origami-build.ft.com/v2/bundles/js?modules=o-expander"></script>
```

...does the second one overwrite the `Origami` global exported by the first one? Or does each script check for an existing `Origami` global and just append its own new properties if found? i.e. will I end up with a single global called `Origami` with two properties `'o-expander'` _and_ `'o-tracking'`?

**Comment by JakeChampion** [comment]
It overrides the original: 

```html
<script async src="https://origami-build.ft.com/v2/bundles/js?modules=o-tracking"></script>
```
Does this:
```js
window["Origami"] = {
    "o-tracking": __webpack_require__(2),
    "o-autoinit": __webpack_require__(85)
};
```

```html
<script async src="https://origami-build.ft.com/v2/bundles/js?modules=o-expander"></script>
```
Does this:
```js
window["Origami"] = {
    "o-expander": __webpack_require__(4),
    "o-autoinit": __webpack_require__(23)
};
```

**Comment by JakeChampion** [comment]
You can define the named of the global object that the origami modules assign to, that way you can have more than one script on a page.

https://www.ft.com/__origami/service/build/v2/bundles/js?modules=o-tracking&export=IG
https://www.ft.com/__origami/service/build/v2/bundles/js?modules=o-expander&export=Origami

**Comment by callumlocke** [comment]
Oh, that's surprising. Would it be possible to change that? It's a common pattern for libs to either create or augment a global namespace, depending on if it's already there.

Something like:

```js
const exports = {
    "o-expander": __webpack_require__(4),
    "o-autoinit": __webpack_require__(23)
};

window["Origami"] = Object.assign({}, window["Origami"], exports);
```

(nb. the above should work correctly even when `window["Origami"]` is undefined, as `Object.assign` skips over any null/undefined sources without throwing)

**Comment by JakeChampion** [comment]
It might be possible but would require an unknown amount of work. Currently what we do is build the bundle with webpack and stream the response to the browser.

**Comment by callumlocke** [comment]
OK that does sound a bit webpacky, I'll continue using workarounds
