### ISSUE TITLE
Clarification on polyfills

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/origami-build-service#119]
Need clarification on this:

> `polyfills` (Optional) If present and set to 'none', does not add polyfills to the output. Use this if your bundle is conflicting with other polyfills (e.g. through the Polyfill Service).

Which polyfills are we talking about? What features do I need to get from polyfill service if I set `polyfills=none` on the build service?

**Comment by JakeChampion** [comment]
Currently build service bundles the babel-polyfill set inside the JS bundle. If you set `polyfills=none`, you will not get the babel-polyfill set. The polyfills you need from polyfill service will vary upon your codebase. I.E. If you are using `Map`s, you will need the `Map` polyfill etc.

The main issue comes down to if you are using new syntax which relies on new JS features such as `for..of`, if using `for..of` you will need to polyfill the `@@iterator` methods on whatever Object types you are iterating over. `NodeList.prototype.@@iterator`, `Array.prototype.@@iterator` etc.
