### ISSUE TITLE
Unversioned urls whitelist to move users to versioned urls

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/origami-build-service#12]
We talked about generating a whitelist based on our logs of users currently using the unversioned build service url (`/bundles` instead of `/v2/bundles`) and not allowing any further users to use the unversioned one, forcing them to add the explicit version to the url

**Comment by JakeChampion** [comment]
This ticket is now out-of-date, we have chosen to redirect instead for less breakage.
