### ISSUE TITLE
Whitelist components allowed to generate demos

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-service#136]
Whitelist the components allowed to have demos compiled (Only Origami components). We can probably do this by checking that the component exists on the Origami Bower registry.

Currently it is possible to compile demos for any component on the global Bower registry.

**Comment by Limess** [comment]
@JakeChampion would it be preferable to limit this to the Origami Bower registry, or components with `origami.json`?

The former can be done ahead of install, the latter would need to be post-install.
