### ISSUE TITLE
Suggestion: Use `.env` for development environment variables instead of `docker-compose.yml`

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-service#18]
Currently the README advocates [storing confidential environment variables inside `docker-compose.yml` for local development](https://github.com/Financial-Times/origami-build-service/tree/docker#configuration). This becomes a bit messy because that file is included within git but will become personal to each developer's set-up (API keys, auth tokens, database names etc). A developer may accidentally commit their environment variables into the git history (which is a bad thing _tm_).

Have you thought about using [`dotenv`](https://www.npmjs.com/package/dotenv) instead of placing the environment variables within `docker-compose.yml`?

`docker-compose.yml` is commited into the repo whereas `.env` can be ignored in `.gitignore`. This means confidential env vars can be stored in it safely and because the file is ignored by git it won't be deployed to production.

**Comment by onishiweb** [comment]
:+1:
