### ISSUE TITLE
Issue: ESM module support

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-service#194]
## What
Reading about [pika web](https://www.pikapkg.com/about/) got me to thinking about how similar moves could make the build service esm module ready, and reduce the need for bundlers.

## Description

e.g. could `import { oThingy, oGoody } from 'https://build.origami/....` in your script

Raises the question of whether there should be convenience urls for individual modules e.g. `https://www.ft.com/__origami/service/build/v2/esm/o-thingy@semver`, and that all of these import their deps rather than bundling

Just an idea for discussion rather than a serious feature request at this stage. Though I would happily be a beta tester

**Comment by JakeChampion** [comment]
This is something we are not looking to implement within the build service, as noted already there are several CDN services which provide this functionality already such as:
- [Skypack](https://www.skypack.dev/)
- [JSPM](https://jspm.org/jspm-dev-release)
- [Unpkg](https://unpkg.com/)

Origami components are already usable as ES Modules via those services 👍
