### ISSUE TITLE
Error if no brand query parameter

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#199]
Let's be explicit and remove the idea of a default brand.

**Comment by chee** [comment]
@JakeChampion is this included in the v3 of the build service?

**Comment by JakeChampion** [comment]
Yes :-) https://github.com/Financial-Times/origami-build-service/blob/4571e6a7c7028403c9b9ac64d339549e36b9a6a7/lib/middleware/v3/parseBrandParameter.js#L15-L18
