### ISSUE TITLE
For Bower/Github - switch from using a username and password to an OAuth token

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-service#20]
Currently OBS uses a Github username and password in order to access any private repositories. It might be a safer approach to use an OAuth token which can be limited to just reading private repositories rather than using an account which may have more privileges than necessary.

**Comment by AlbertoElias** [comment]
:+1:

**Comment by JakeChampion** [comment]
The line of code in master where this happens --> https://github.com/Financial-Times/origami-build-service/blob/master/index.js#L33

**Comment by Limess** [comment]
I think this just needs a credentials update on heroku with the relevant token rather than a code change? Github OAuth token as password in basic auth is allowed I think.

**Comment by JakeChampion** [comment]
@Limess Let's try it out on the QA Heroku application :-D

**Comment by JakeChampion** [comment]
This has just been completed!
