### ISSUE TITLE
Refactor the tests to run in the container

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-build-service#21]
Ideally the tests should be runnable in either the container or the developer's machine. Currently they're pretty much only runnable on the dev machine. In CI we probably want to run the integration tests against the container.

**Comment by rowanmanning** [comment]
I think we should leave this until we've sped up the container build. Currently it'd really slow down CI if we built the Docker image on all branches.

**Comment by JakeChampion** [comment]
This issue is now outdated. We've removed Docker from our services as it is unstable.
