### ISSUE TITLE
demo issue?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#217]
[n-notification](https://github.com/Financial-Times/n-notification) demos aren't working because..?

**Comment by chee** [comment]
this is weird

**Comment by chee** [comment]
https://www.ft.com/__origami/service/build/v2/demos/n-notification@7.0.2/all?brand=master

it says

```
 Demo template not found: ./bower_components/n-notification/demos/src/all.html 
```

but it should be looking at either demos/src/all.mustache (mentioned in the origami.json) or `demos/local/all.html` (built by the service)

**Comment by chee** [comment]
https://github.com/Financial-Times/origami-build-service/blob/f9f060a8cac380c41d329916f024147a579b3773/lib/build-tools/tasks/demo.js#L20

https://github.com/Financial-Times/origami-build-service/blob/f9f060a8cac380c41d329916f024147a579b3773/lib/build-tools/tasks/demo.js#L26-L28

https://github.com/Financial-Times/n-notification/blob/master/origami.json#L31

??

**Comment by JakeChampion** [comment]
I just fixed it 👍 The component had a demo/src/config.json as well as a origami.json demos definition. Removing the redundant config.json file fixed the issue.

https://registry.origami.ft.com/components/n-notification@7.0.3/
