### ISSUE TITLE
Find a replacement for the diskspace module

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-build-service#22]
The module is unreliable and it gets free space values by parsing a table output by the `df` command. The `df` command output is different on different Linux distributions, which caused some issues when moving to Alpine.

Also we currently maintain a forked version of the module and so have to install it through git. We could remove git as a dependency and reduce the container size if we find a good npm-hosted module.

**Comment by JakeChampion** [comment]
Potential alternative which uses statvfs for *nix systems -- https://www.npmjs.com/package/diskusage

**Comment by JakeChampion** [comment]
Heroku creates a [fresh filesystem whenever a dyno is restarted](https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem). Heroku also [restart dynos every 24 hours (+- 216 minutes)](https://devcenter.heroku.com/articles/dynos#restarting), which means the filesystem is cleared once a day. Do we know if the filesystem use has been an issue before?

**Comment by rowanmanning** [comment]
I don't think this is happening, at least not any time soon. Gonna close this for now, we don't even use Alpine any more which is why we were originally gonna do this
