### ISSUE TITLE
Use HTTPS by default

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-build-service#3]
_[originally reported by @AlbertoElias]_

**Comment by rowanmanning** [comment]
We'll get this automatically when we migrate fully to Fastly – I've set it up to redirect HTTP to HTTPS on the edge. We can close this once we close #8 and #9.

**Comment by JakeChampion** [comment]
This is on hold whilst we look into the issues this is causing with next-geebee.

**Comment by JakeChampion** [comment]
We only serve over https now
