### ISSUE TITLE
Use origami-repo-data to fetch list of components to add to the npm cache upon server booting up

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-service#400]
Currently the project is using a fixed this.This probably shouldn't exist as a fixed list.
It should use an origami-repo-data api call to get the list similar to origami-component-converter and fallback to a fixed list if the origami-repo-data api call fails.

We can reuse some code in origami component converter which does a similar thing --
https://github.com/Financial-Times/origami-component-converter/blob/10990dac98e980594a329f0cd68537b0e51a6560/lib/npm.js#L8-L17

_Originally posted by @JakeChampion in https://github.com/Financial-Times/origami-build-service/pull/391#discussion_r532691930_

**Comment by chee** [comment]
If we're going to be doing an Origami repo data call, then we can also perhaps build this web page too: https://github.com/Financial-Times/origami-build-service/issues/39

what do you think?

**Comment by JakeChampion** [comment]
> If we're going to be doing an Origami repo data call, then we can also perhaps build this web page too: #39
> 
> what do you think?

That's a great idea 👍
