### ISSUE TITLE
Add migration for the `v3/files` endpoint

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#409]
- The main usecase for the `files` endpoint is to include font files from `o-fonts-assets`. 
- Other uses appear to be old component assets ([file endpoint Splunk statistics](https://financialtimes.splunkcloud.com/en-GB/app/search/search?sid=1608031697.3000470)). 
- No current component version includes assets in this way. None will in the same way going forward, as it will not work with npm. There's [a proposal for handling component assets](https://github.com/Financial-Times/origami/pull/102) in the future.
- If we require a system code to include fonts, and pass through the system code of the project consuming Origami, the client won't cache fonts between pages of the ft (pretty major, fonts are heavy)
- Instead we decided it would be better to remove the file endpoint from v3 and host fonts in S3. We could do this just for `o-fonts-assets` in whatever way is easiest, or perhaps we go ahead and [implement the asset proposal for all components](https://github.com/Financial-Times/origami/pull/102)?

Relates to: https://github.com/Financial-Times/origami-build-service/pull/408

**Comment by JakeChampion** [comment]
We've instead opted for having a v3/font API instead 👍 

https://github.com/Financial-Times/origami-build-service/pull/426
