### ISSUE TITLE
v3 suggestion: only accept origami components

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#441]
throw an error if a requested `module` does not include an `origami.json`

**Comment by JakeChampion** [comment]
We should find out how many requests exist on the production version of the build service which request non origami modules. We can find this out by querying the logs in splunk.

This query will return a count of all the different bundle requests we have in the last month -- 

https://financialtimes.splunkcloud.com/en-GB/app/search/search?sid=1612953242.21233855
