### ISSUE TITLE
v2: Deprecate the use of `modules` for anything that's not an Origami component. 

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#444]
Deprecate the use of `modules` for anything that's not an Origami component.  Potentially create an allow list
to do this. Motivation:
- ensure arbitrary code cannot be bundled by non-ft users
- ensure new users don't come to depend on this feature, which has no upgrade path to v3

Relates to: https://github.com/Financial-Times/origami-build-service/issues/441
>This query will return a count of all the different bundle requests we have in the last month --
>https://financialtimes.splunkcloud.com/en-GB/app/search/search?sid=1612953242.21233855

**Comment by JakeChampion** [comment]
Is this a duplicate of https://github.com/Financial-Times/origami-build-service/issues/455?

**Comment by notlee** [comment]
huh, yes, 👍 closing for https://github.com/Financial-Times/origami-build-service/issues/455
