### ISSUE TITLE
v3: support non `o-` names

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#454]
I happened to spot an assumption that component names begin with `o-` in the codebase:
https://github.com/Financial-Times/origami-build-service/blob/8932e483fce442423ffa19dd0485174e6b21d48b/lib/middleware/v3/createEntryFileSass.js#L24

[That's not necessarily true](https://origami.ft.com/spec/v1/components/#naming-conventions), `o-` is encouraged but not enforced, e.g. g-audio.

Task: add v3 tests for CSS bundles, JS bundles, and demos of Origami compatible components with a name not prefixed with `o-`.

**Comment by JakeChampion** [comment]
> Task: add v3 tests for CSS bundles, JS bundles, and demos of Origami compatible components with a name not prefixed with `o-`.

Good idea! This requires making a new test origami component. We could publish o-test-component under two names? `test-component` and `o-test-component`... Or we could just start publishing it as `test-component`?

What do we think @Financial-Times/origami-core?
