### ISSUE TITLE
v3: feature request, error when a bundle is requested for components at the latest version

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#456]
v2 defaults to old versions of components when "latest", "*", or no version is requested. That is because
a major release of o-tracking, and potentially other components, caused many breaking builds across
different projects. 

https://github.com/Financial-Times/origami-build-service/blob/59b0e0d2bf63112dbd8ab52951aa2b2efb62ffec/lib/middleware/defaultModuleVersions.js#L30

To avoid this situation for v3 we should consider throwing an error when components are requested
at the latest version, or requested without a version range specified.

Though for short lived examples/prototypes it can be helpful to request a bundle for a component without 
looking up its latest version first, the trade off of breaking builds in the future doesn't seem worth it.

Note I don't think this should affect demo endpoints as demos are self contained — it would be reasonable
to embed a component demo for the latest version, the demo wouldn't break given a major release

**Comment by JakeChampion** [comment]
> To avoid this situation for v3 we should consider throwing an error when components are requested
> at the latest version, or requested without a version range specified.

v3 already does this, it returns an error if no semver range/version is specified
https://github.com/Financial-Times/origami-build-service/blob/7e1eadd5721073a1eda69d50c74c80116f655beb/lib/middleware/v3/parseModulesParameter.js#L79-L81

>Note I don't think this should affect demo endpoints as demos are self contained — it would be reasonable
to embed a component demo for the latest version, the demo wouldn't break given a major release

The pull-request for v3 demos currently also returns an error if no semver range/version is specified. -- https://github.com/Financial-Times/origami-build-service/pull/460/files#diff-8c1eb431d6f3aeb9fdd100579f1a61e65164acf12417a903bb4a54b420541f56R52-R54

**Comment by notlee** [comment]
>v3 already does this

oh, nice!

>The pull-request for v3 demos currently also returns an error

Cool, I think that's fine. I was thinking before that showing the latest demo could be useful for pages like the [branding documentation](https://origami.ft.com/docs/components/branding/), but using a specific version will always be safer (a future demo isn't guaranteed to show the same thing, in the same way). So let's leave it as is and close this issue until we have a more compelling reason to allow requests for the latest version of demos.

Turns out v2 errors when requesting the latest version of a demo [since we restricted to valid semver ranges](https://github.com/Financial-Times/origami-build-service/pull/443). It's broken the [branding documentation](https://origami.ft.com/docs/components/branding/) 🙈 I'll open a Build Service v2 PR to allow `latest` requests again,
since we don't know what other pages may be affected.
![Screenshot 2021-03-01 at 11 15 51](https://user-images.githubusercontent.com/10405691/109490012-8c681a00-7a7f-11eb-808e-fc906f6a465f.png)

**Comment by JakeChampion** [comment]
> Turns out v2 errors when requesting the latest version of a demo [since we restricted to valid semver ranges](https://github.com/Financial-Times/origami-build-service/pull/443). It's broken the [branding documentation](https://origami.ft.com/docs/components/branding/) 🙈 I'll open a Build Service v2 PR to allow `latest` requests again,

That should work with the semver range `*` rather than the `latest` keyword, have you tried that?

**Comment by JakeChampion** [comment]
> So let's leave it as is and close this issue until we have a more compelling reason to allow requests for the latest version of demos.

Closing this issue 👍
