### ISSUE TITLE
Add time notification to npm install

### ISSUE THREAD

**Issue by j-mes** [Financial-Times/origami-build-service#47]
After undergoing the `npm install` on OBS build on a pretty old Mac mini which took 12 minutes. I think a notification either by the terminal or via OS X to inform you when the task has been completed would be incredibly useful to have.

[How do I make a Mac terminal pop up alert via AppleScript](http://stackoverflow.com/questions/5588064/how-do-i-make-a-mac-terminal-pop-up-alert-applescript)

**Comment by AlbertoElias** [comment]
I'm personally not a big fan of this, it was suggested to add notifications to OBT a while back ago, but there wasn't much acceptance of the idea. Normally, if you're working on OBS, that's just something you're paying attention to.

That's just my personal opinion, I wouldn't be bothered if it was added

**Comment by j-mes** [comment]
Doesn't necessarily have to be a notification within OS X but something at the end in terminal to acknowledge it's been done and how long it took to do the task?

**Comment by rowanmanning** [comment]
Would an OK solution just be to use the `time` command? That way a dev can choose whether to add it before they run a command, or only add it if they're trying to make improvements to the speed of things. E.g.

```sh
$ time npm install

  some-module@1.2.3
  └── some-other-module@3.2.1

  real    0m18.371s
  user    0m14.628s
  sys     0m3.413s
```

**Comment by rowanmanning** [comment]
Gonna close this for now 👍
