### ISSUE TITLE
Update URL Updater

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#518]
Update the URL updater to better support OBS v2 to v3.

E.g. v3 requires a:
- a source parameter
- a brand parameter

Consider an input to get these if they don't already exist on a given v2 url.

**Comment by JakeChampion** [comment]
Origami Build Service v3 does not include o-autoinit by default. When we add the ability for the url-updater to convert v2 to v3 urls, we will need to include o-autoinit in the components query-parameter, unless the v2 url contains the autoinit query-parameter set to `0`
