### ISSUE TITLE
Limit v3 to bundling origami type "component" projects 

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-service#524]
E.g. do not bundle libraries.

https://financialtimes.slack.com/archives/CSW6B2VAN/p1619694098127900

**Comment by JakeChampion** [comment]
I think during the specification review we decided that the build-service should support origami libraries, we also spoke about changing o-normalise and I think o-autoinit from `component` to `library`, and those will very likely be things build-service users will want to request in their bundles

**Comment by notlee** [comment]
As we have deprecated the spec and therefore o-normalise and o-autoinit no longer break it, shall we leave those as components for now and close this issue?
