### ISSUE TITLE
Add task for image sets

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/origami-build-service#69]
Currently, for image sets to appear in the registry, they must have a file could ImageList.json in their root which lists all of the images to show in the registry. See https://github.com/Financial-Times/fticons for the schema.

This imageList has to be kept up to date in order for the registry demo to match up with what's live. This is normally done by people remembering to run the gulp task that creates the list. 

This is bad because (1) people forget (2) we have a gulp task across multiple copied across multiple repos (3) we introduce a dependency on gulp which a lot of people who contribute to various image sets don't have installed.

A good solution would be to move this behaviour (generating an index of images in the /src/ folder and putting it in the root) to the build service.

**Comment by JakeChampion** [comment]
We decided to keep this feature out of OBS and use CI to build the `imageList.json` files in each image set repository, whenever they are updated.
