### ISSUE TITLE
Add Continuous deployment

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/origami-build-service#7]
Easy to do with circle

**Comment by rowanmanning** [comment]
Update on this: we can't quite add continuous deployment because of this issue https://github.com/heroku/heroku-docker/issues/138

We have two options:

1. Wait for this issue to be fixed, which could take a while.
2. Move to official Heroku Docker support, which is currently in private beta.

**Comment by JakeChampion** [comment]
I don't think the issue will get fixed as Heroku are no longer advocating use of their Heroku Docker plugin which creates slugs. This means the option left is to use their Docker registry which is in private beta.

**Comment by rowanmanning** [comment]
I think we've decided that 2 is the better option because of this :)

**Comment by rowanmanning** [comment]
We're doing this now
