### ISSUE TITLE
Add CORS header to JS build endpoint 

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/origami-build-service#76]
So that I can use the `crossorigin=anonymous` attribute on script tags to get better error info.

Also o-cookie-message uses local storage so doesn't always work with the build service.

**Comment by JakeChampion** [comment]
@kavanagh Is the issue with o-cookie-message solved by adding the CORS header? If not, could you open a second issue which explains how to replicate the o-cookie-message issue please?

**Comment by kavanagh** [comment]
Umm, you're probably right that it won't make a difference. 

The o-cookie-message value _should_ get saved against the `origami-build.ft.com` localStorage. But I'm getting some weird errors in Sentry about the Cookie Message and I can't really see what the problem is. Once I can understand those errors a bit more I may have something useful to raise as a second issue.

**Comment by kavanagh** [comment]
I've just done a little bit of digging and raised two issues:

1. [o-cookie-message#20](https://github.com/Financial-Times/o-cookie-message/issues/20)
2. [o-cookie-message#21](https://github.com/Financial-Times/o-cookie-message/issues/21)

**Comment by JakeChampion** [comment]
This is now live #79
