### ISSUE TITLE
Stale while revalidate

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/origami-build-service#8]
For a bundle that has previously been built by the build service, I never want to have to wait for a synchronous build of it again, regardless of how frequently it is requested.

**Comment by rowanmanning** [comment]
The build service is currently [sending this header](https://github.com/Financial-Times/origami-build-service/blob/master/lib/utils/index.js#L15-L16) (and the one mentioned in #9), however Akamai currently doesn't honour them. We're intending on moving to Fastly, which [honours stale-while-revalidate](https://www.fastly.com/blog/stale-while-revalidate-stale-if-error-available-today).

**Comment by JakeChampion** [comment]
Serving stale whilst revalidating is live. The migration to Fastly is now complete - http://origami-build.ft.com/v2/#fastly-migration
